default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: PgrsTest_development
  username: postgres
  password: password

test:
  <<: *default
  database: PgrsTest_test
  username: postgres
  password: password

production:
  <<: *default
  database: PgrsTest_production
  username: postgres
  password: password
